version: "3.8"
services:
  web:
    build: ./app
    image: 228841907158.dkr.ecr.us-east-2.amazonaws.com/spencercms_docker_aws
    command: python app.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:5000
    environment:
      - DB_NAME=cms_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=cms.c0h1kjfybabt.us-east-2.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-3-17-91-180.us-east-2.compute.amazonaws.com
      - VIRTUAL_PORT=8000
   

